places_remember/memories/urls.py
from django.urls import path
from .views import (
    MemoryListView,
    MemoryCreateView,
    MemoryDetailView,
    MemoryDeleteView,
    MemoryUpdateView,
)


urlpatterns = [
    # path('', show_main_page()),
    path("", MemoryListView.as_view(), name="memories"),
    path("create", MemoryCreateView.as_view(), name="create"),
    path("<int:pk>", MemoryDetailView.as_view(), name="detail"),
    path("<int:pk>/delete", MemoryDeleteView.as_view(), name="delete"),
    path("<int:pk>/edit", MemoryUpdateView.as_view(), name="edit"),
]

places_remember/places_remember/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from users.views import show_login_page

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", show_login_page),
    path("", include("social_django.urls", namespace="social")),
    path("logout/", LogoutView.as_view(template_name="login_page.html"), name="logout"),
    path("memories/", include(("memories.urls", "memories"), namespace="memories")),
]

places_remember/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/base.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'styles/fonts.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block scripts %}
    {% endblock %}
    {% block style %}
    {% endblock %}
    <title>{% block title %}{% endblock %} | Place Remember</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark fixed-top">
        <div class="container">
                <a href="{% url 'memories:memories' %}">
                    <div class="avatar-name">
                        <img class="avatar" src="{{ user.avatar }}">
                        <span class="username">{{ user.first_name }} {{ user.last_name }}</span>
                    </div>
                </a>
                <a href="{% url 'memories:create' %}">
                    <button type="button" class="btn btn-dark btn-lg">
                        Добавить воспоминание
                      </button>
                </a>
                <a href="{% url 'logout' %}">
                    <button class="btn btn-outline-light">
                        Выйти
                    </button>
                </a>
        </div>

    </nav>
    <div class="container" style="margin-top: 5rem;">
        <div class="row">
            <!-- <div class="col-lg-12"> -->
                {% block content %}

                {% endblock %}
            <!-- </div> -->
        </div>
    </div>
</body>
</html>

places_remember/templates/login_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/login.css' %}">
    <link rel="stylesheet" href="{% static 'styles/fonts.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock %}
    {% block style %}
    {% endblock %}
    <title>Place Remember</title>
</head>
<body>
    <div class="container">
        <div class="col-lg-6 offset-lg-3">
            <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">

                <div class="form">
                    <h1 class="title">Place Remember</h1>
                    <!-- <div class="about">
                        Доброго дня! Вы зашли на сайт, служащий хранилищем воспоминаний о разных местах! Загружайте фотографии,
                        отмечайте места на карте, делитесь впечатлениями :)
                    </div> -->

                    <div class="buttons">
                        <a href="/login/vk-oauth2">
                            <button class="btn">
                                <img src="{% static 'media/vk_icon.svg' %}" alt="" class="btn-icon">
                                Войти с помощью VK
                            </button>
                        </a>

                        <a href="/login/google-oauth2">
                            <button class="btn">
                                <img src="{% static 'media/google_icon.svg' %}" alt="" class="btn-icon">
                                Войти с помощью Google
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>