places_remember/memories/urls.py
from django.urls import path
from .views import (
    MemoryListView,
    MemoryCreateView,
    MemoryDetailView,
    MemoryDeleteView,
    MemoryUpdateView,
)


urlpatterns = [
    # path('', show_main_page()),
    path("", MemoryListView.as_view(), name="memories"),
    path("create", MemoryCreateView.as_view(), name="create"),
    path("<int:pk>", MemoryDetailView.as_view(), name="detail"),
    path("<int:pk>/delete", MemoryDeleteView.as_view(), name="delete"),
    path("<int:pk>/edit", MemoryUpdateView.as_view(), name="edit"),
]

places_remember/places_remember/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from users.views import show_login_page

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", show_login_page),
    path("", include("social_django.urls", namespace="social")),
    path("logout/", LogoutView.as_view(template_name="login_page.html"), name="logout"),
    path("memories/", include(("memories.urls", "memories"), namespace="memories")),
]

places_remember/memories/models.py
from django.db import models
from users.models import CustomUser


class Memory(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False, default=None)
    user_id = models.ForeignKey(CustomUser, blank=True, on_delete=models.CASCADE)
    place = models.CharField(max_length=255, blank=True, null=True, default=None)
    created = models.DateField(auto_now_add=True, auto_now=False)
    description = models.TextField(blank=True, null=True, default=None)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "Memory"
        verbose_name_plural = "Memories"


class Image(models.Model):
    memory = models.ForeignKey(
        Memory, blank=True, null=True, default=None, on_delete=models.CASCADE
    )
    image = models.ImageField(
        default="static/media/placeholder.png", upload_to="static/media/test_user"
    )
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self) -> str:
        return "Photo from {0}".format(self.memory)

    class Meta:
        verbose_name = "Image"
        verbose_name_plural = "Images"

places_remember/memories/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Memory, Image
from django.forms import inlineformset_factory
from django.core.exceptions import ValidationError


class AddMemoryForm(forms.ModelForm):
    class Meta:
        model = Memory
        fields = ["name", "description", "place", "user_id"]
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "form-control",
                    # 'style': 'max-width: 300px;',
                    "placeholder": "Название",
                }
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "form-control",
                    # 'style': 'max-width: 300px;',
                    "placeholder": "Описание",
                }
            ),
            "place": forms.HiddenInput(),
            "user_id": forms.HiddenInput(),
        }

    def clean_place(self):
        place = self.cleaned_data["place"]
        if not place:
            raise ValidationError("Выберите место на карте")
        return place


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        image = forms.ImageField()
        fields = "__all__"
        widgets = {
            "image": CustomClearableFileInput,
            "delete": forms.CheckboxInput(
                attrs={
                    "class": "form-check-input",
                    "type": "checkbox",
                    "value": "",
                }
            ),
        }

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     for field in self.fields:
    #         print(field)


ImageFormset = inlineformset_factory(
    Memory, Image, extra=3, max_num=6, can_delete=True, fields=["image"], form=ImageForm
)

places_remember/memories/views.py
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy
from .forms import AddMemoryForm
from .models import Memory
from .forms import ImageFormset
from django.shortcuts import redirect
from django.http import Http404


class ObjectViewMixin:
    model = None
    allow_empty = False

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            self.object = self.get_object(
                self.model.objects.filter(user_id=request.user)
            )
        else:
            raise Http404("Page not found")
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class ObjectUpdateViewMixin(ObjectViewMixin):
    def get_context_data(self, **kwargs):
        context = super(UpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context["image_formset"] = ImageFormset(
                self.request.POST, self.request.FILES, instance=self.object
            )
        else:
            context["image_formset"] = ImageFormset(instance=self.object)
        return context

    def form_valid(self, form, image_formset):
        self.object = form.save(commit=False)
        self.object.user_id = self.request.user
        self.object.save()

        images = image_formset.save(commit=False)
        image_formset.instance = self.object
        for image in images:
            image.memory = self.object
            image.save()
        image_formset.save()
        return redirect(self.success_url)

    def form_invalid(self, form, image_formset):
        return self.render_to_response(
            self.get_context_data(form=form, image_formset=image_formset)
        )


class MemoryListView(ListView):
    model = Memory
    context_object_name = "memories"
    # allow_empty = False

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Memory.objects.filter(user_id=self.request.user)
        else:
            raise Http404("Page not found")
        return Memory.objects.none()


class MemoryDetailView(ObjectViewMixin, DetailView):
    model = Memory
    context_object_name = "memory"
    pk_url_kwarg = "pk"


class MemoryDeleteView(ObjectViewMixin, DeleteView):
    model = Memory
    success_url = reverse_lazy("memories:memories")


class MemoryCreateView(ObjectUpdateViewMixin, CreateView):
    model = Memory
    form_class = AddMemoryForm
    success_url = reverse_lazy("memories:memories")

    def get_context_data(self, **kwargs):
        context = super(CreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context["image_formset"] = ImageFormset(
                self.request.POST, self.request.FILES
            )
        else:
            context["image_formset"] = ImageFormset()
        return context

    def get(self, request, *args, **kwargs):
        self.object = None
        if not self.request.user.is_authenticated:
            raise Http404("Page not found")
        return self.render_to_response(self.get_context_data())

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        image_formset = ImageFormset(
            self.request.POST, self.request.FILES, instance=self.object
        )
        if form.is_valid() and image_formset.is_valid():
            return self.form_valid(form, image_formset)
        return self.form_invalid(form, image_formset)


class MemoryUpdateView(ObjectUpdateViewMixin, UpdateView):
    model = Memory
    form_class = AddMemoryForm
    success_url = reverse_lazy("memories:memories")
    context_object_name = "memory"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object(self.model.objects.filter(user_id=request.user))
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        image_formset = ImageFormset(
            self.request.POST, self.request.FILES, instance=self.object
        )
        if form.is_valid() and image_formset.is_valid():
            return self.form_valid(form, image_formset)
        return self.form_invalid(form, image_formset)

places_remember/templates/memories/memory_confirm_delete.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block scripts %}
    {% endblock %}
    {% block style %}
    <link rel="stylesheet" href="{% static 'styles/memory_delete.css' %}">
    {% endblock %}
    <title>{% block title %}Удаление {{ memory.name }}{% endblock %}</title>
</head>
<body>
    {% block content %}
    <div class="col-lg-6 offset-lg-3">
        <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
            <form method="post">{% csrf_token %}
                <h1 class="confirmation-title">Вы точно хотите удалить "{{ memory.name }}"?</h1>
                {{ form }}
                <div class="action-btns">
                    <input type="submit" value="Удалить" class="btn btn-danger">
                    <a class="btn btn-outline-light" href="{% url 'memories:memories' %}">Cancel</a>
                </div>
            </form>
        </div>
    </div>
    {% endblock %}
</body>
</html>

places_remember/templates/memories/memory_detail.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block scripts %}
    <script src="https://api-maps.yandex.ru/2.1/?apikey=d44c7945-2d1c-407c-849f-666a20744ccc&lang=ru_RU" type="text/javascript"></script>
    <script src="{% static 'js/yandex_maps.js' %}" type="text/javascript" ></script>
    {% endblock %}
    {% block style %}
    <link rel="stylesheet" href="{% static 'styles/memory_detail.css' %}">
    {% endblock %}

    <title>{% block title %}{{object.name}}{% endblock %}</title>
</head>
<body>
    {% block content %}

        <h1>{{object.name}}</h1>
        <!-- <p>Name: {{object.name}}</p> -->
        {% if object.description != '' %}
            <span class="description">{{object.description}}</span>
        {% else %}
            <span class="description">Описание не заполнено</span>
        {% endif %}
        <p id="id_place">{{object.place.as_hidden}}</p>
        <!-- <p>User: {{object.user_id}}</p> -->
        <div class="col-lg-8 photos">
            {% if object.image_set.all %}
                {% for image in object.image_set.all %}
                    <img class="memory-photo" src="{{ image.image.url }}" alt="photo">
                {% endfor %}
            {% else %}
                <h4>Нет фото</h4>
            {% endif %}
        </div>
        <div class="col-lg-4">
            <div class="toolbar">
                <img class="map" src="https://static-maps.yandex.ru/1.x/?ll={{object.place}}&pt={{object.place}},comma&l=map&size=450,450&z=13" alt="map">
                <a href="{% url 'memories:edit' pk=memory.pk %}">
                    <button class="btn btn-outline-secondary btn-lg">
                        Редактировать
                    </button>
                </a>
                <a href="{% url 'memories:delete' pk=memory.pk %}">
                    <button class="btn btn-outline-danger btn-lg">
                        Удалить
                    </button>
                </a>
            </div>
        </div>
    {% endblock %}
</body>
</html>

places_remember/templates/memories/memory_form.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block scripts %}
    <script src="https://api-maps.yandex.ru/2.1/?apikey=d44c7945-2d1c-407c-849f-666a20744ccc&lang=ru_RU&coordorder=longlat" type="text/javascript"></script>
    <script src="{% static 'js/yandex_maps.js' %}" type="text/javascript" ></script>
    {% endblock %}
    {% block style %}
    <link rel="stylesheet" href="{% static 'styles/memory_form.css' %}">
    {% endblock %}

    <title>
      {% block title %}
      {% if form.name.value %}
      {{ form.name.value }}
      {% else %}
      Новое воспоминание
      {% endif %}
      {% endblock %}
    </title>
</head>
<body>
  {% block content %}
  <div class="col-lg-6 offset-3">
    <div class="toolbar">
      {% if form.name.value %}
      <h1>{{ form.name.value }}</h1>
      {% else %}
      <h1>Новое воспоминание</h1>
      {% endif %}
      <a href="{% url 'memories:memories' %}">
        <button class="btn btn-outline-danger">
            Отмена
        </button>
      </a>
    </div>

    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-error">{{ form.errors.place }}</div>
      <div class="form">
        {% for field in form %}
          {{field}}
        {% endfor %}


      <!-- {{ form }} -->

        {{ image_formset.management_form }}
        <!-- {{ image_formset.non_form_errors }} -->


        {% for form in image_formset.forms %}
        <!-- {% if form.place == "" %}
        <span>Укажите место на карте</span>
        {% endif %} -->
        <div class="inline-form">
          {% for field in form %}

            <div>
               {% if field.label == "Image" %}
              {{field}}
              {% elif field.label == "Delete" %}
                Удалить: {{field}}
              {% endif %}
              {{ field.as_hidden }}
            </div>

          {% endfor %}
        </div>
        {% endfor %}
        <div id="map" style="width: auto; height: 500px;"></div>
          <input type="submit" value="Save" class="btn btn-outline-success"/>
        </div>
      </div>

    </form>
  {% endblock %}

</body>
</html>

places_remember/templates/memories/memory_list.html
{% extends "base.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block scripts %}
    <script src="https://api-maps.yandex.ru/2.1/?apikey=d44c7945-2d1c-407c-849f-666a20744ccc&lang=ru_RU" type="text/javascript"></script>
    <script src="{% static 'js/yandex_maps.js' %}" type="text/javascript" ></script>
    {% endblock %}
    {% block style %}
    <link rel="stylesheet" href="{% static 'styles/memory_list.css' %}">
    {% endblock %}
    <title>{% block title %}{{ user.first_name }} {{ user.last_name }}{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% for memory in memories %}
    <div class="col-lg-3">
        <div class="memory-card">
            <a class="memory-title" href="{% url 'memories:detail' pk=memory.pk %}"><h3>{{ memory.name }}</h3></a>


            <a href="{% url 'memories:edit' pk=memory.pk %}">
                <button class="btn btn-outline-light btn-lg">
                    Редактировать
                </button>
            </a>

            <a href="{% url 'memories:delete' pk=memory.pk %}">
                <button class="btn btn-outline-danger btn-lg">
                    Удалить
                </button>
            </a>

            <!-- <p>
                {% for memory_image in memory.image_set.all %}
                    <img src="{{ memory_image.image.url }}" alt="photo", width="350px">
                {% endfor %}
            </p> -->
        </div>
    </div>
    {% endfor %}

    {% endblock %}
</body>
</html>